// Shared tokens, helpers, i18n, and common components for the Kazan prototype
// All exported to window so other Babel scripts can use them

const fmtKZT = (n, lang) => {
  const formatted = new Intl.NumberFormat(lang === 'ru' ? 'ru-RU' : 'en-US').format(Math.round(n));
  return `${formatted} ₸`;
};

const I18N = {
  en: {
    nav_shop: 'Shop',
    nav_journal: 'Journal',
    nav_research: 'Research',
    nav_about: 'About',
    tab_storefront: 'Storefront',
    tab_dashboard: 'Research dashboard',
    hero_eyebrow: 'Edition Nº 01 — Spring 2026',
    hero_title_a: 'Small kitchens.',
    hero_title_b: 'Long journeys.',
    hero_sub: 'A curated index of portable appliances for cabins, road trips, dorms, and offices — assembled, weighed, and shipped from Almaty.',
    hero_cta: 'Browse the catalogue',
    hero_cta_alt: 'How we choose',
    hero_meta: '5 categories · 1,000 SKUs · ships across CIS',
    sec_categories: 'Categories',
    sec_categories_sub: 'Five tightly-edited shelves. Every item travels.',
    sec_for_you: 'For you',
    sec_for_you_sub: 'Hybrid recommender — collaborative signal + content features',
    sec_popular: 'Reading the room',
    sec_popular_sub: 'Most-purchased this season',
    sec_journal: 'From the journal',
    cat_label: 'Category',
    sku_label: 'SKU',
    in_stock: 'In stock',
    add_to_cart: 'Add to cart',
    buy_now: 'Buy now',
    you_might: 'Pairs well with',
    you_might_sub: 'Generated by the hybrid model — collaborative similarity weighted with content features.',
    cart_title: 'Your basket',
    cart_empty: 'Your basket is empty.',
    cart_subtotal: 'Subtotal',
    cart_shipping: 'Shipping',
    cart_total: 'Total',
    cart_checkout: 'Proceed to checkout',
    cart_continue: 'Continue browsing',
    free: 'Free',
    qty: 'Qty',
    remove: 'Remove',
    back: 'Back',
    pdp_overview: 'Overview',
    pdp_specs: 'Specifications',
    pdp_shipping: 'Delivery',
    pdp_brand: 'Brand',
    pdp_voltage: 'Voltage',
    pdp_capacity: 'Capacity',
    pdp_warranty: 'Warranty',
    pdp_voltage_v: '110–240 V universal',
    pdp_capacity_v: 'Travel-class',
    pdp_warranty_v: '24 months',
    pdp_ship_v: 'Almaty same-day · CIS 3–7 days',
    footer_a: 'Kazan, Almaty.',
    footer_b: 'A research prototype. Не для продажи.',
    footer_c: 'Thesis P2773314 · De Montfort University · 2026',
    pop_rank: 'Demand index',
    rec_strip_label: 'Recommended for you',
    review_count: 'reviews'
  },
  ru: {
    nav_shop: 'Каталог',
    nav_journal: 'Журнал',
    nav_research: 'Исследование',
    nav_about: 'О нас',
    tab_storefront: 'Магазин',
    tab_dashboard: 'Панель исследования',
    hero_eyebrow: 'Выпуск №01 — весна 2026',
    hero_title_a: 'Маленькие кухни.',
    hero_title_b: 'Длинные дороги.',
    hero_sub: 'Кураторская подборка портативных приборов для дач, командировок, общежитий и офисов — собрано, взвешено и отправляется из Алматы.',
    hero_cta: 'Перейти в каталог',
    hero_cta_alt: 'Как мы выбираем',
    hero_meta: '5 категорий · 1 000 SKU · доставка по СНГ',
    sec_categories: 'Категории',
    sec_categories_sub: 'Пять тщательно подобранных полок. Всё путешествует.',
    sec_for_you: 'Для вас',
    sec_for_you_sub: 'Гибридная модель — коллаборативный сигнал + контентные признаки',
    sec_popular: 'Что читают',
    sec_popular_sub: 'Лидеры продаж сезона',
    sec_journal: 'Из журнала',
    cat_label: 'Категория',
    sku_label: 'Артикул',
    in_stock: 'В наличии',
    add_to_cart: 'В корзину',
    buy_now: 'Купить сейчас',
    you_might: 'С этим берут',
    you_might_sub: 'Сформировано гибридной моделью — коллаборативное сходство, взвешенное контентными признаками.',
    cart_title: 'Корзина',
    cart_empty: 'Ваша корзина пуста.',
    cart_subtotal: 'Подытог',
    cart_shipping: 'Доставка',
    cart_total: 'Итого',
    cart_checkout: 'К оформлению',
    cart_continue: 'Продолжить покупки',
    free: 'Бесплатно',
    qty: 'Кол-во',
    remove: 'Удалить',
    back: 'Назад',
    pdp_overview: 'Обзор',
    pdp_specs: 'Характеристики',
    pdp_shipping: 'Доставка',
    pdp_brand: 'Бренд',
    pdp_voltage: 'Напряжение',
    pdp_capacity: 'Объём',
    pdp_warranty: 'Гарантия',
    pdp_voltage_v: '110–240 В универсальное',
    pdp_capacity_v: 'Travel-class',
    pdp_warranty_v: '24 месяца',
    pdp_ship_v: 'Алматы — день в день · СНГ 3–7 дней',
    footer_a: 'Kazan, Алматы.',
    footer_b: 'Прототип для исследования. Not for sale.',
    footer_c: 'Дипломная работа P2773314 · De Montfort University · 2026',
    pop_rank: 'Индекс спроса',
    rec_strip_label: 'Рекомендации для вас',
    review_count: 'отзывов'
  }
};

const CATEGORY_META = {
  'Portable Kettle':  { en: 'Portable Kettle',  ru: 'Дорожный чайник',  short: 'KETTLE',  hue: 22 },
  'Multi-Cooker':     { en: 'Multi-Cooker',     ru: 'Мультиварка',       short: 'COOKER',  hue: 188 },
  'Rice Cooker':      { en: 'Rice Cooker',      ru: 'Рисоварка',         short: 'RICE',    hue: 48 },
  'Coffee Maker':     { en: 'Coffee Maker',     ru: 'Кофеварка',         short: 'COFFEE',  hue: 12 },
  'Portable Blender': { en: 'Portable Blender', ru: 'Блендер',           short: 'BLEND',   hue: 152 }
};

// Striped SVG placeholder, parameterised by hue + label
function ProductPlaceholder({ category, size = 'md', label }) {
  const meta = CATEGORY_META[category] || { short: 'ITEM', hue: 30 };
  const id = `pat-${category.replace(/\s/g,'')}-${Math.random().toString(36).slice(2,6)}`;
  const heights = { sm: 140, md: 240, lg: 360, xl: 520 };
  const h = heights[size] || 240;
  return (
    <div className="kz-image" style={{ height: h }}>
      <svg width="100%" height="100%" viewBox="0 0 400 400" preserveAspectRatio="xMidYMid slice" aria-hidden="true">
        <defs>
          <pattern id={id} width="14" height="14" patternUnits="userSpaceOnUse" patternTransform="rotate(35)">
            <rect width="14" height="14" fill="var(--kz-cream)"/>
            <line x1="0" y1="0" x2="0" y2="14" stroke="var(--kz-cream-2)" strokeWidth="6"/>
          </pattern>
        </defs>
        <rect width="400" height="400" fill={`url(#${id})`}/>
        <rect x="0.5" y="0.5" width="399" height="399" fill="none" stroke="var(--kz-line)" strokeWidth="1"/>
      </svg>
      <div className="kz-image-label">
        <span className="kz-mono">{meta.short}</span>
        <span className="kz-mono kz-image-label-thin">{label || 'product photo'}</span>
      </div>
    </div>
  );
}

// Deterministic hash for stable "ratings" / mock data per id
function hash(n, salt = 0) {
  let x = (n + salt) | 0;
  x = (x ^ 61) ^ (x >>> 16);
  x = x + (x << 3);
  x = x ^ (x >>> 4);
  x = Math.imul(x, 0x27d4eb2d);
  x = x ^ (x >>> 15);
  return ((x >>> 0) % 10000) / 10000;
}

function ratingFor(id) {
  // 4.0 – 4.9
  return (4.0 + hash(id, 7) * 0.9).toFixed(1);
}
function reviewsFor(id) {
  return Math.floor(20 + hash(id, 13) * 480);
}

// Category icon: minimal line glyph (kept simple per system rules — only basic shapes)
function CatGlyph({ category, size = 28 }) {
  const c = category;
  const stroke = 'currentColor';
  const sw = 1.4;
  const s = size;
  const common = { width: s, height: s, viewBox: '0 0 32 32', fill: 'none', stroke, strokeWidth: sw, strokeLinecap: 'round', strokeLinejoin: 'round' };
  if (c === 'Portable Kettle')
    return (<svg {...common}><path d="M7 12h14l-1.5 12a2 2 0 0 1-2 2H10.5a2 2 0 0 1-2-2L7 12z"/><path d="M21 14l4 -2"/><circle cx="14" cy="18" r="0.8" fill={stroke}/></svg>);
  if (c === 'Multi-Cooker')
    return (<svg {...common}><rect x="6" y="11" width="20" height="14" rx="1.5"/><path d="M10 11V8h12v3"/><circle cx="22" cy="17" r="0.8" fill={stroke}/><path d="M9 25v2M23 25v2"/></svg>);
  if (c === 'Rice Cooker')
    return (<svg {...common}><path d="M5 15c0-1 .5-2 2-2h18c1.5 0 2 1 2 2v8c0 1.5-1 2.5-2.5 2.5h-17C6 25.5 5 24.5 5 23v-8z"/><path d="M9 13c0-2 1.5-3 3-3h8c1.5 0 3 1 3 3"/></svg>);
  if (c === 'Coffee Maker')
    return (<svg {...common}><path d="M9 8h12v6c0 4-2.5 7-6 7s-6-3-6-7V8z"/><path d="M21 11h2a2 2 0 0 1 0 4h-2"/><path d="M8 26h14"/></svg>);
  if (c === 'Portable Blender')
    return (<svg {...common}><path d="M11 6h10l-1 8H12l-1-8z"/><rect x="12" y="14" width="8" height="10" rx="1"/><path d="M14 24v2M18 24v2"/></svg>);
  return (<svg {...common}><rect x="6" y="6" width="20" height="20"/></svg>);
}

// Hairline rule
function Rule({ vertical, style }) {
  return <div className={`kz-rule ${vertical ? 'kz-rule-v' : ''}`} style={style}/>;
}

Object.assign(window, {
  fmtKZT, I18N, CATEGORY_META,
  ProductPlaceholder, CatGlyph, Rule,
  hash, ratingFor, reviewsFor
});
