"""
Content-based recommender using TF-IDF

This model represents each product as a TF-IDF vector computed from its
text description, category, and brand. It then builds a user profile by
averaging the TF-IDF vectors of items the user has purchased, weighted by
purchase count. Recommendations are generated by finding items most similar
(cosine similarity) to the user profile

Key concepts:
- TF-IDF converts text into numerical vectors where
  each dimension is a word, and the value reflects how important that word
  is to a specific document relative to the corpus
- Cosine similarity measures the angle between two vectors, ignoring magnitude.
  Two items with similar descriptions will have vectors pointing in similar
  directions regardless of description length
"""

import os
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse


class ContentModel:
    def __init__(self):
        self.tfidf_matrix = None
        self.vectorizer = None
        self.n_items = 0

    def fit(self, products_df, interaction_matrix):
        """
        Build TF-IDF vectors for all products

        We combine category, brand, and English description into a single
        text field per product before vectorizing

        Parameters
        ----------
        products_df : DataFrame
            Must have columns: category, brand, description_en
        interaction_matrix : sparse CSR matrix (items x users)
            Stored for building user profiles at recommendation time
        """
        self.interaction_matrix = interaction_matrix
        self.n_items = len(products_df)

        # Combine text features into a single string per product
        combined_text = (
            products_df["category"] + " " +
            products_df["brand"] + " " +
            products_df["description_en"]
        )

        # Fit TF-IDF. max_features caps vocabulary to avoid noise from
        # extremely rare words, ngram_range=(1,2) captures bigrams like
        # "stainless steel" or "auto shut-off" as single features
        self.vectorizer = TfidfVectorizer(
            max_features=5000,
            ngram_range=(1, 2),
            stop_words="english",
        )
        self.tfidf_matrix = self.vectorizer.fit_transform(combined_text)

    def _build_user_profile(self, user_id, interaction_matrix):
        """
        Build a user profile by averaging TF-IDF vectors of purchased items,
        weighted by purchase count

        A user who bought a blender 5 times contributes that blender's TF-IDF
        vector 5x more to their profile than a single-purchase item. This
        mirrors the confidence concept from ALS
        """
        user_col = interaction_matrix.tocsc()[:, user_id]
        purchased_items = user_col.nonzero()[0]
        purchase_counts = np.array(user_col[purchased_items].todense()).flatten()

        if len(purchased_items) == 0:
            return None

        # Weighted average of TF-IDF vectors
        item_vectors = self.tfidf_matrix[purchased_items]
        weights = purchase_counts.reshape(-1, 1)
        profile = np.array((item_vectors.multiply(weights)).mean(axis=0)).flatten()

        return profile

    def recommend(self, user_id, interaction_matrix, k=10):
        """
        Recommend items most similar to the user's content profile.
        """
        profile = self._build_user_profile(user_id, interaction_matrix)

        if profile is None:
            # Cold-start: no interactions, can't build a profile
            return []

        # Cosine similarity between user profile and all items
        similarities = cosine_similarity(
            profile.reshape(1, -1), self.tfidf_matrix
        ).flatten()

        # Exclude already purchased items
        already_seen = set(interaction_matrix.tocsc()[:, user_id].nonzero()[0])
        for item in already_seen:
            similarities[item] = -1

        top_k = np.argsort(similarities)[::-1][:k]
        return top_k.tolist()

    def get_item_similarities(self, item_id, k=10):
        """
        Returns the K most similar items to a given item based on content
        Useful for "similar products" features on the website
        """
        sim = cosine_similarity(
            self.tfidf_matrix[item_id], self.tfidf_matrix
        ).flatten()
        sim[item_id] = -1  # exclude self
        top_k = np.argsort(sim)[::-1][:k]
        return top_k.tolist()

    def score_items(self, user_id, interaction_matrix):
        """
        Returns a score for every item based on content similarity to user profile
        Used by the hybrid model to combine with ALS scores
        """
        profile = self._build_user_profile(user_id, interaction_matrix)

        if profile is None:
            return np.zeros(self.n_items)

        similarities = cosine_similarity(
            profile.reshape(1, -1), self.tfidf_matrix
        ).flatten()

        return similarities
